export default `
<datosDeInventario>
  <inventario>
        <productos>
            <producto>
                <codigo>00001</codigo>
                <nombre>Camiseta del Real Madrid</nombre>
                <categoria>Ropa</categoria>
                <precio>49000</precio>
                <costo>24000</costo>
                <existencia>15</existencia>
                <exisVerificadas>15</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>30</stockMax>
            </producto>
            <producto>
                <codigo>00002</codigo>
                <nombre>Auriculares Bluetooth</nombre>
                <categoria>Tecnología</categoria>
                <precio>89000</precio>
                <costo>45000</costo>
                <existencia>25</existencia>
                <exisVerificadas>24</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>50</stockMax>
            </producto>
            <producto>
                <codigo>00003</codigo>
                <nombre>Smartwatch</nombre>
                <categoria>Tecnología</categoria>
                <precio>129000</precio>
                <costo>60000</costo>
                <existencia>30</existencia>
                <exisVerificadas>29</exisVerificadas>
                <stockMin>5</stockMin>
                <stockMax>60</stockMax>
            </producto>
            <producto>
                <codigo>00004</codigo>
                <nombre>Mochila Deportiva</nombre>
                <categoria>Accesorios</categoria>
                <precio>39000</precio>
                <costo>18000</costo>
                <existencia>20</existencia>
                <exisVerificadas>20</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>40</stockMax>
            </producto>
            <producto>
                <codigo>00005</codigo>
                <nombre>Laptop Gaming</nombre>
                <categoria>Tecnología</categoria>
                <precio>1200000</precio>
                <costo>850000</costo>
                <existencia>10</existencia>
                <exisVerificadas>9</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>20</stockMax>
            </producto>
            <producto>
                <codigo>00006</codigo>
                <nombre>Botella Térmica</nombre>
                <categoria>Accesorios</categoria>
                <precio>25000</precio>
                <costo>12000</costo>
                <existencia>35</existencia>
                <exisVerificadas>34</exisVerificadas>
                <stockMin>5</stockMin>
                <stockMax>70</stockMax>
            </producto>
            <producto>
                <codigo>00007</codigo>
                <nombre>Teclado Mecánico</nombre>
                <categoria>Tecnología</categoria>
                <precio>150000</precio>
                <costo>90000</costo>
                <existencia>12</existencia>
                <exisVerificadas>12</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>24</stockMax>
            </producto>
            <producto>
                <codigo>00008</codigo>
                <nombre>Zapatillas Running</nombre>
                <categoria>Ropa</categoria>
                <precio>99000</precio>
                <costo>50000</costo>
                <existencia>18</existencia>
                <exisVerificadas>18</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>36</stockMax>
            </producto>
            <producto>
                <codigo>00009</codigo>
                <nombre>Cámara Digital</nombre>
                <categoria>Tecnología</categoria>
                <precio>500000</precio>
                <costo>300000</costo>
                <existencia>8</existencia>
                <exisVerificadas>7</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>16</stockMax>
            </producto>
            <producto>
                <codigo>00010</codigo>
                <nombre>Gafas de Sol</nombre>
                <categoria>Accesorios</categoria>
                <precio>45000</precio>
                <costo>22000</costo>
                <existencia>28</existencia>
                <exisVerificadas>28</exisVerificadas>
                <stockMin>4</stockMin>
                <stockMax>56</stockMax>
            </producto>
            <producto>
                <codigo>00011</codigo>
                <nombre>Chaqueta Deportiva</nombre>
                <categoria>Ropa</categoria>
                <precio>120000</precio>
                <costo>70000</costo>
                <existencia>14</existencia>
                <exisVerificadas>14</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>28</stockMax>
            </producto>
            <producto>
                <codigo>00012</codigo>
                <nombre>Monitor 4K</nombre>
                <categoria>Tecnología</categoria>
                <precio>800000</precio>
                <costo>550000</costo>
                <existencia>6</existencia>
                <exisVerificadas>6</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>12</stockMax>
            </producto>
            <producto>
                <codigo>00013</codigo>
                <nombre>Ratón Inalámbrico</nombre>
                <categoria>Tecnología</categoria>
                <precio>35000</precio>
                <costo>18000</costo>
                <existencia>22</existencia>
                <exisVerificadas>22</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>44</stockMax>
            </producto>
            <producto>
                <codigo>00014</codigo>
                <nombre>Camiseta Running</nombre>
                <categoria>Ropa</categoria>
                <precio>49000</precio>
                <costo>24000</costo>
                <existencia>15</existencia>
                <exisVerificadas>15</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>30</stockMax>
            </producto>
            <producto>
                <codigo>00015</codigo>
                <nombre>Tablet Android</nombre>
                <categoria>Tecnología</categoria>
                <precio>350000</precio>
                <costo>220000</costo>
                <existencia>9</existencia>
                <exisVerificadas>9</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>18</stockMax>
            </producto>
            <producto>
                <codigo>00016</codigo>
                <nombre>Bolso de Mano</nombre>
                <categoria>Accesorios</categoria>
                <precio>60000</precio>
                <costo>30000</costo>
                <existencia>20</existencia>
                <exisVerificadas>19</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>40</stockMax>
            </producto>
            <producto>
                <codigo>00017</codigo>
                <nombre>Smartphone</nombre>
                <categoria>Tecnología</categoria>
                <precio>700000</precio>
                <costo>500000</costo>
                <existencia>10</existencia>
                <exisVerificadas>10</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>20</stockMax>
            </producto>
            <producto>
                <codigo>00018</codigo>
                <nombre>Sandalias de Playa</nombre>
                <categoria>Ropa</categoria>
                <precio>35000</precio>
                <costo>18000</costo>
                <existencia>25</existencia>
                <exisVerificadas>25</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>50</stockMax>
            </producto>
            <producto>
                <codigo>00019</codigo>
                <nombre>Consola de Videojuegos</nombre>
                <categoria>Tecnología</categoria>
                <precio>1500000</precio>
                <costo>1000000</costo>
                <existencia>5</existencia>
                <exisVerificadas>5</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>10</stockMax>
            </producto>
            <producto>
                <codigo>00020</codigo>
                <nombre>Reloj Análogo</nombre>
                <categoria>Accesorios</categoria>
                <precio>120000</precio>
                <costo>60000</costo>
                <existencia>12</existencia>
                <exisVerificadas>12</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>24</stockMax>
            </producto>
            <producto>
                <codigo>00021</codigo>
                <nombre>Gorra Deportiva</nombre>
                <categoria>Ropa</categoria>
                <precio>25000</precio>
                <costo>12000</costo>
                <existencia>30</existencia>
                <exisVerificadas>30</exisVerificadas>
                <stockMin>4</stockMin>
                <stockMax>60</stockMax>
            </producto>
            <producto>
                <codigo>00022</codigo>
                <nombre>Disco Duro Externo</nombre>
                <categoria>Tecnología</categoria>
                <precio>200000</precio>
                <costo>150000</costo>
                <existencia>15</existencia>
                <exisVerificadas>14</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>30</stockMax>
            </producto>
            <producto>
                <codigo>00023</codigo>
                <nombre>Cargador Inalámbrico</nombre>
                <categoria>Tecnología</categoria>
                <precio>70000</precio>
                <costo>35000</costo>
                <existencia>18</existencia>
                <exisVerificadas>18</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>36</stockMax>
            </producto>
            <producto>
                <codigo>00024</codigo>
                <nombre>Sudadera Deportiva</nombre>
                <categoria>Ropa</categoria>
                <precio>89000</precio>
                <costo>45000</costo>
                <existencia>14</existencia>
                <exisVerificadas>14</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>28</stockMax>
            </producto>
            <producto>
                <codigo>00025</codigo>
                <nombre>Auriculares de Diadema</nombre>
                <categoria>Tecnología</categoria>
                <precio>110000</precio>
                <costo>65000</costo>
                <existencia>12</existencia>
                <exisVerificadas>12</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>24</stockMax>
            </producto>
            <producto>
                <codigo>00026</codigo>
                <nombre>Chaqueta de Invierno</nombre>
                <categoria>Ropa</categoria>
                <precio>150000</precio>
                <costo>90000</costo>
                <existencia>10</existencia>
                <exisVerificadas>10</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>20</stockMax>
            </producto>
            <producto>
                <codigo>00027</codigo>
                <nombre>Cámara de Acción</nombre>
                <categoria>Tecnología</categoria>
                <precio>300000</precio>
                <costo>200000</costo>
                <existencia>7</existencia>
                <exisVerificadas>7</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>14</stockMax>
            </producto>
            <producto>
                <codigo>00028</codigo>
                <nombre>Guantes Deportivos</nombre>
                <categoria>Ropa</categoria>
                <precio>29000</precio>
                <costo>15000</costo>
                <existencia>20</existencia>
                <exisVerificadas>20</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>40</stockMax>
            </producto>
            <producto>
                <codigo>00029</codigo>
                <nombre>Smart TV</nombre>
                <categoria>Tecnología</categoria>
                <precio>2000000</precio>
                <costo>1500000</costo>
                <existencia>5</existencia>
                <exisVerificadas>5</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>10</stockMax>
            </producto>
            <producto>
                <codigo>00030</codigo>
                <nombre>Correa de Cuero</nombre>
                <categoria>Accesorios</categoria>
                <precio>55000</precio>
                <costo>30000</costo>
                <existencia>16</existencia>
                <exisVerificadas>16</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>32</stockMax>
            </producto>
            <producto>
                <codigo>00031</codigo>
                <nombre>Botas de Montaña</nombre>
                <categoria>Ropa</categoria>
                <precio>200000</precio>
                <costo>120000</costo>
                <existencia>8</existencia>
                <exisVerificadas>8</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>16</stockMax>
            </producto>
            <producto>
                <codigo>00032</codigo>
                <nombre>Audífonos In-Ear</nombre>
                <categoria>Tecnología</categoria>
                <precio>60000</precio>
                <costo>30000</costo>
                <existencia>20</existencia>
                <exisVerificadas>20</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>40</stockMax>
            </producto>
            <producto>
                <codigo>00033</codigo>
                <nombre>Camiseta Casual</nombre>
                <categoria>Ropa</categoria>
                <precio>40000</precio>
                <costo>20000</costo>
                <existencia>22</existencia>
                <exisVerificadas>22</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>44</stockMax>
            </producto>
            <producto>
                <codigo>00034</codigo>
                <nombre>Juego de Llaves</nombre>
                <categoria>Accesorios</categoria>
                <precio>25000</precio>
                <costo>15000</costo>
                <existencia>30</existencia>
                <exisVerificadas>29</exisVerificadas>
                <stockMin>4</stockMin>
                <stockMax>60</stockMax>
            </producto>
            <producto>
                <codigo>00035</codigo>
                <nombre>Bicicleta de Montaña</nombre>
                <categoria>Deportes</categoria>
                <precio>1000000</precio>
                <costo>700000</costo>
                <existencia>5</existencia>
                <exisVerificadas>5</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>10</stockMax>
            </producto>
            <producto>
                <codigo>00036</codigo>
                <nombre>Pantalones Cortos</nombre>
                <categoria>Ropa</categoria>
                <precio>55000</precio>
                <costo>28000</costo>
                <existencia>18</existencia>
                <exisVerificadas>18</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>36</stockMax>
            </producto>
            <producto>
                <codigo>00037</codigo>
                <nombre>Linterna LED</nombre>
                <categoria>Accesorios</categoria>
                <precio>20000</precio>
                <costo>10000</costo>
                <existencia>25</existencia>
                <exisVerificadas>25</exisVerificadas>
                <stockMin>4</stockMin>
                <stockMax>50</stockMax>
            </producto>
            <producto>
                <codigo>00038</codigo>
                <nombre>Camiseta de Algodón</nombre>
                <categoria>Ropa</categoria>
                <precio>30000</precio>
                <costo>15000</costo>
                <existencia>20</existencia>
                <exisVerificadas>20</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>40</stockMax>
            </producto>
            <producto>
                <codigo>00039</codigo>
                <nombre>Parlante Bluetooth</nombre>
                <categoria>Tecnología</categoria>
                <precio>150000</precio>
                <costo>90000</costo>
                <existencia>12</existencia>
                <exisVerificadas>12</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>24</stockMax>
            </producto>
            <producto>
                <codigo>00040</codigo>
                <nombre>Mochila Escolar</nombre>
                <categoria>Accesorios</categoria>
                <precio>45000</precio>
                <costo>22000</costo>
                <existencia>18</existencia>
                <exisVerificadas>18</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>36</stockMax>
            </producto>
            <producto>
                <codigo>00041</codigo>
                <nombre>Silla Ergonómica</nombre>
                <categoria>Muebles</categoria>
                <precio>250000</precio>
                <costo>150000</costo>
                <existencia>10</existencia>
                <exisVerificadas>10</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>20</stockMax>
            </producto>
            <producto>
                <codigo>00042</codigo>
                <nombre>Bicicleta Estática</nombre>
                <categoria>Deportes</categoria>
                <precio>800000</precio>
                <costo>500000</costo>
                <existencia>7</existencia>
                <exisVerificadas>7</exisVerificadas>
                <stockMin>1</stockMin>
                <stockMax>14</stockMax>
            </producto>
            <producto>
                <codigo>00043</codigo>
                <nombre>Camiseta Polo</nombre>
                <categoria>Ropa</categoria>
                <precio>60000</precio>
                <costo>30000</costo>
                <existencia>15</existencia>
                <exisVerificadas>15</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>30</stockMax>
            </producto>
            <producto>
                <codigo>00044</codigo>
                <nombre>Auriculares In-Ear</nombre>
                <categoria>Tecnología</categoria>
                <precio>50000</precio>
                <costo>25000</costo>
                <existencia>20</existencia>
                <exisVerificadas>20</exisVerificadas>
                <stockMin>3</stockMin>
                <stockMax>40</stockMax>
            </producto>
            <producto>
                <codigo>00045</codigo>
                <nombre>Mesa de Camping</nombre>
                <categoria>Muebles</categoria>
                <precio>85000</precio>
                <costo>45000</costo>
                <existencia>12</existencia>
                <exisVerificadas>12</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>24</stockMax>
            </producto>
            <producto>
                <codigo>00046</codigo>
                <nombre>Bolsa de Dormir</nombre>
                <categoria>Accesorios</categoria>
                <precio>65000</precio>
                <costo>35000</costo>
                <existencia>14</existencia>
                <exisVerificadas>14</exisVerificadas>
                <stockMin>2</stockMin>
                <stockMax>28</stockMax>
            </producto>
        </productos>
    </inventario>
  <fechaUltimaVerificacion>string</fechaUltimaVerificacion>
  <verifPdtes>
        <modificacion fechaHora="string">
            <cantidadProductosIngresados>0</cantidadProductosIngresados>
            <cantidadProductosRetirados>0</cantidadProductosRetirados>
            <cantidadDeCorrecciones>0</cantidadDeCorrecciones>
        </modificacion>
  </verifPdtes>
</datosDeInventario>`;
