export default `
<datosDeVitrina>
	<actividadReciente>
		<inactividad>15</inactividad>
		<ultimaVenta>
			<prod1>
				<nombre>Adaptador Universal,</nombre>
				<cantidad>1</cantidad>
			</prod1>
			<prod2>
				<nombre>Gorra de Colombia,</nombre>
				<cantidad>3</cantidad>
			</prod2>
			<masProductos>true</masProductos>
			<valor>95.000</valor>
			<fecha>Ayer, a las 8:35pm </fecha>
		</ultimaVenta>
		<ventasDelDia>
			<cantidad>20</cantidad>
			<porcentajeDeCrecimiento>10</porcentajeDeCrecimiento>
		</ventasDelDia>
	</actividadReciente>
	<actividadGeneral>
		<ventaMesActual>
			<valor>900.000</valor>
			<porcentajeDeCrecimiento>15</porcentajeDeCrecimiento>
		</ventaMesActual>
		<ventasDeUltimosMeses>
			 <ventaDeMes>
                <mes>Abr</mes>
                <valor>0</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>May</mes>
                <valor>4000</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>Jun</mes>
                <valor>1000</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>Jul</mes>
                <valor>3000</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>Ago</mes>
                <valor>2000</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>Sept</mes>
                <valor>4000</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>Oct</mes>
                <valor>5000</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>Nov</mes>
                <valor>500</valor>
            </ventaDeMes>
            <ventaDeMes>
                <mes>Dic</mes>
                <valor>10000</valor>
            </ventaDeMes>
		</ventasDeUltimosMeses>
		<ventasDeDiasDelMes>
			<ventaDia>
                <dia>0-6am</dia>
                <valor>35</valor>
            </ventaDia>
            <ventaDia>
                <dia>6-10am</dia>
                <valor>32</valor>
            </ventaDia>
            <ventaDia>
                <dia>10am-3pm</dia>
                <valor>30</valor>
            </ventaDia>
            <ventaDia>
                <dia>3-8pm</dia>
                <valor>30</valor>
            </ventaDia>
            <ventaDia>
                <dia>8-12pm</dia>
                <valor>40</valor>
            </ventaDia>
		</ventasDeDiasDelMes>
		<categorias>
            <categoria>
				<nombre>Ropa</nombre>
				<porcentajeDeLasVentas>95</porcentajeDeLasVentas>
			</categoria>
			<categoria>
				<nombre>Artesanías</nombre>
				<porcentajeDeLasVentas>75</porcentajeDeLasVentas>
			</categoria>
			<categoria>
				<nombre>Joyas</nombre>
				<porcentajeDeLasVentas>60</porcentajeDeLasVentas>
			</categoria>
			<categoria>
				<nombre>Tecnología</nombre>
				<porcentajeDeLasVentas>30</porcentajeDeLasVentas>
			</categoria>
			<categoria>
				<nombre>Otros</nombre>
				<porcentajeDeLasVentas>10</porcentajeDeLasVentas>
			</categoria>
		</categorias>
		<intervalosDelDia>
			<intervaloDelDia>
				<intervalo>01/03</intervalo>
				<porcentajeDeVentas>120</porcentajeDeVentas>
			</intervaloDelDia>
            <intervaloDelDia>
				<intervalo>Ayer</intervalo>
				<porcentajeDeVentas>300</porcentajeDeVentas>
			</intervaloDelDia>
            <intervaloDelDia>
				<intervalo>Hoy</intervalo>
				<porcentajeDeVentas>280</porcentajeDeVentas>
			</intervaloDelDia>
		</intervalosDelDia>
	</actividadGeneral>
	<resumenDeVisitas>
		<estadoDelDispositivo>Ok</estadoDelDispositivo>
		<verificacionesPdtes>
			<modificacion>
                <fechaHora>05/07/2024 10:30AM</fechaHora>
                <cantidadProductosIngresados>15</cantidadProductosIngresados>
                <cantidadProductosRetirados>7</cantidadProductosRetirados>
                <cantidadDeCorrecciones>3</cantidadDeCorrecciones>
            </modificacion>
            <modificacion>
                <fechaHora>08/09/2024 4:45PM</fechaHora>
                <cantidadProductosIngresados>20</cantidadProductosIngresados>
                <cantidadProductosRetirados>5</cantidadProductosRetirados>
                <cantidadDeCorrecciones>1</cantidadDeCorrecciones>
            </modificacion>
            <modificacion>
                <fechaHora>12/11/2024 8:15AM</fechaHora>
                <cantidadProductosIngresados>10</cantidadProductosIngresados>
                <cantidadProductosRetirados>12</cantidadProductosRetirados>
                <cantidadDeCorrecciones>2</cantidadDeCorrecciones>
            </modificacion>
            <modificacion>
                <fechaHora>15/12/2024 3:00PM</fechaHora>
                <cantidadProductosIngresados>25</cantidadProductosIngresados>
                <cantidadProductosRetirados>10</cantidadProductosRetirados>
                <cantidadDeCorrecciones>4</cantidadDeCorrecciones>
            </modificacion>
            <modificacion>
                <fechaHora>18/01/2025 11:20AM</fechaHora>
                <cantidadProductosIngresados>30</cantidadProductosIngresados>
                <cantidadProductosRetirados>8</cantidadProductosRetirados>
                <cantidadDeCorrecciones>0</cantidadDeCorrecciones>
            </modificacion>
		</verificacionesPdtes>
		<reposicionesUrg>
			 <producto>
                <nombre>Camisetas</nombre>
                <existenciasActuales>6</existenciasActuales>
                <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Gorras</nombre>
                <existenciasActuales>8</existenciasActuales>
                <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Pantalones</nombre>
                <existenciasActuales>10</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Zapatos</nombre>
                <existenciasActuales>8</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Sudaderas</nombre>
                <existenciasActuales>6</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Chaquetas</nombre>
                <existenciasActuales>4</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Vestidos</nombre>
                <existenciasActuales>9</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Faldas</nombre>
                <existenciasActuales>10</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Calcetines</nombre>
                <existenciasActuales>12</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Bufandas</nombre>
                <existenciasActuales>14</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Guantes</nombre>
                <existenciasActuales>6</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Sombreros</nombre>
                <existenciasActuales>6</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Corbatas</nombre>
                <existenciasActuales>9</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Mochilas</nombre>
                <existenciasActuales>7</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Bolsos</nombre>
                <existenciasActuales>5</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Cinturones</nombre>
                <existenciasActuales>4</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Relojes</nombre>
                <existenciasActuales>8</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Anillos</nombre>
                <existenciasActuales>6</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Collares</nombre>
                <existenciasActuales>6</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
            <producto>
                <nombre>Pulseras</nombre>
                <existenciasActuales>4</existenciasActuales>
                 <cantidadMinima>2</cantidadMinima>
            </producto>
		</reposicionesUrg>
	</resumenDeVisitas>
</datosDeVitrina>
`;
