export default [
  {
    Asesor: "Alejandro Urrutia",
    Vitrinas: "Corales de India",
    Ubicacion: "Cartagena",
    Usuario: "@Alejo",
    Contraseña: "@Alejo",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Mariana Pérez",
    Vitrinas: "Perlas del Caribe",
    Ubicacion: "Barranquilla",
    Usuario: "@MariP",
    Contraseña: "@MariP",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Juan Gómez",
    Vitrinas: "Joyas de Sol",
    Ubicacion: "Santa Marta",
    Usuario: "@JuanG",
    Contraseña: "@JuanG",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Lucía Martínez",
    Vitrinas: "Tesoros del Pacífico",
    Ubicacion: "Buenaventura",
    Usuario: "@LuciaM",
    Contraseña: "@LuciaM",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Carlos López",
    Vitrinas: "Esmeraldas del Amazonas",
    Ubicacion: "Leticia",
    Usuario: "@CarlosL",
    Contraseña: "@CarlosL",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Laura Torres",
    Vitrinas: "Oro de los Andes",
    Ubicacion: "Bogotá",
    Usuario: "@LauraT",
    Contraseña: "@LauraT",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Santiago Díaz",
    Vitrinas: "Rubíes de la Sierra",
    Ubicacion: "Manizales",
    Usuario: "@SantiD",
    Contraseña: "@SantiD",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Valeria Ramírez",
    Vitrinas: "Diamantes del Llano",
    Ubicacion: "Villavicencio",
    Usuario: "@ValeR",
    Contraseña: "@ValeR",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Miguel Castro",
    Vitrinas: "Cristales de la Sabana",
    Ubicacion: "Chía",
    Usuario: "@MiguelC",
    Contraseña: "@MiguelC",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Daniela Moreno",
    Vitrinas: "Topacios del Cauca",
    Ubicacion: "Popayán",
    Usuario: "@DaniM",
    Contraseña: "@DaniM",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Ricardo Ortiz",
    Vitrinas: "Zafiros del Magdalena",
    Ubicacion: "Santa Marta",
    Usuario: "@RickyO",
    Contraseña: "@RickyO",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Andrea Rodríguez",
    Vitrinas: "Amatistas de la Sierra",
    Ubicacion: "Pasto",
    Usuario: "@AndreaR",
    Contraseña: "@AndreaR",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Fernando Sánchez",
    Vitrinas: "Opalos del Quindío",
    Ubicacion: "Armenia",
    Usuario: "@FerS",
    Contraseña: "@FerS",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Camila Vargas",
    Vitrinas: "Cuarzos del Tolima",
    Ubicacion: "Ibagué",
    Usuario: "@CamiV",
    Contraseña: "@CamiV",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Sebastián Gil",
    Vitrinas: "Turquesas de los Llanos",
    Ubicacion: "Yopal",
    Usuario: "@SebaG",
    Contraseña: "@SebaG",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Isabel Muñoz",
    Vitrinas: "Granates del Chocó",
    Ubicacion: "Quibdó",
    Usuario: "@IsaM",
    Contraseña: "@IsaM",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Tomás Ríos",
    Vitrinas: "Jades del Huila",
    Ubicacion: "Neiva",
    Usuario: "@TomasR",
    Contraseña: "@TomasR",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Juliana Paredes",
    Vitrinas: "Aguamarinas del Valle",
    Ubicacion: "Cali",
    Usuario: "@JuliP",
    Contraseña: "@JuliP",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Cristian Rojas",
    Vitrinas: "Peridotos del Cesar",
    Ubicacion: "Valledupar",
    Usuario: "@CrisR",
    Contraseña: "@CrisR",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Natalia Castillo",
    Vitrinas: "Berilos de Bolívar",
    Ubicacion: "Cartagena",
    Usuario: "@NatiC",
    Contraseña: "@NatiC",
    Hab_Des: "Habilitar / deshabilitar para modificarr",
  },
  {
    Asesor: "Luis Fernández",
    Vitrinas: "Espinelas de Sucre",
    Ubicacion: "Sincelejo",
    Usuario: "@LuisF",
    Contraseña: "@LuisF",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Paula Soto",
    Vitrinas: "Crisoberilos de Meta",
    Ubicacion: "Villavicencio",
    Usuario: "@PaulaS",
    Contraseña: "@PaulaS",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Álvaro Cárdenas",
    Vitrinas: "Labradoritas de Putumayo",
    Ubicacion: "Mocoa",
    Usuario: "@AlvaroC",
    Contraseña: "@AlvaroC",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Sara Gutiérrez",
    Vitrinas: "Iolitas de Vaupés",
    Ubicacion: "Mitú",
    Usuario: "@SaraG",
    Contraseña: "@SaraG",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Mateo Herrera",
    Vitrinas: "Calcedonias de Guaviare",
    Ubicacion: "San José del Guaviare",
    Usuario: "@MateoH",
    Contraseña: "@MateoH",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Antonia Londoño",
    Vitrinas: "Sardónices de Guainía",
    Ubicacion: "Inírida",
    Usuario: "@AntoniaL",
    Contraseña: "@AntoniaL",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Gabriel Pino",
    Vitrinas: "Aventurinas del Amazonas",
    Ubicacion: "Leticia",
    Usuario: "@GabrielP",
    Contraseña: "@GabrielP",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Mónica García",
    Vitrinas: "Ópalos de Nariño",
    Ubicacion: "Pasto",
    Usuario: "@MonicaG",
    Contraseña: "@MonicaG",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Diego Castillo",
    Vitrinas: "Ágatas de Santander",
    Ubicacion: "Bucaramanga",
    Usuario: "@DiegoC",
    Contraseña: "@DiegoC",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Jazmín Díaz",
    Vitrinas: "Cornalinas del Magdalena",
    Ubicacion: "Santa Marta",
    Usuario: "@JazminD",
    Contraseña: "@JazminD",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
  {
    Asesor: "Esteban Moreno",
    Vitrinas: "Heliodoros del Atlántico",
    Ubicacion: "Barranquilla",
    Usuario: "@EstebanM",
    Contraseña: "@EstebanM",
    Hab_Des: "Habilitar / deshabilitar para modificar",
  },
];
