export default [
  {
    Producto: "Zapatos Deportivos",
    Codigo: "00002",
    Precio: "$120.00",
    Costo: "$100.00",
    Bodega: 150,
    Vitrinas: 50,
    Proveedor: "Juan Gómez",
    Categorias: "Calzado",
  },
  {
    Producto: "Gafas de Sol",
    Codigo: "00003",
    Precio: "$75.00",
    Costo: "$50.00",
    Bodega: 300,
    Vitrinas: 80,
    Proveedor: "Luis Martínez",
    Categorias: "Accesorios",
  },
  {
    Producto: "Bolso de Mano",
    Codigo: "00004",
    Precio: "$90.00",
    Costo: "$60.00",
    Bodega: 100,
    Vitrinas: 40,
    Proveedor: "Ana López",
    Categorias: "Moda",
  },
  {
    Producto: "Reloj Deportivo",
    Codigo: "00005",
    Precio: "$150.00",
    Costo: "$110.00",
    Bodega: 200,
    Vitrinas: 90,
    Proveedor: "Carlos Sánchez",
    Categorias: "Tecnología",
  },
  {
    Producto: "Cartera de Cuero",
    Codigo: "00006",
    Precio: "$85.00",
    Costo: "$45.00",
    Bodega: 80,
    Vitrinas: 30,
    Proveedor: "María García",
    Categorias: "Moda",
  },
  {
    Producto: "Auriculares Inalámbricos",
    Codigo: "00007",
    Precio: "$60.00",
    Costo: "$35.00",
    Bodega: 250,
    Vitrinas: 120,
    Proveedor: "José Rodríguez",
    Categorias: "Tecnología",
  },
  {
    Producto: "Camiseta Deportiva",
    Codigo: "00008",
    Precio: "$30.00",
    Costo: "$20.00",
    Bodega: 400,
    Vitrinas: 150,
    Proveedor: "Laura Hernández",
    Categorias: "Ropa",
  },
  {
    Producto: "Pantalones Vaqueros",
    Codigo: "00009",
    Precio: "$50.00",
    Costo: "$35.00",
    Bodega: 200,
    Vitrinas: 90,
    Proveedor: "Miguel Fernández",
    Categorias: "Ropa",
  },
  {
    Producto: "Chaqueta de Cuero",
    Codigo: "00010",
    Precio: "$180.00",
    Costo: "$120.00",
    Bodega: 60,
    Vitrinas: 20,
    Proveedor: "Patricia Ramírez",
    Categorias: "Ropa",
  },
  {
    Producto: "Zapatillas de Casa",
    Codigo: "00011",
    Precio: "$25.00",
    Costo: "$15.00",
    Bodega: 300,
    Vitrinas: 100,
    Proveedor: "Rafael Torres",
    Categorias: "Calzado",
  },
  {
    Producto: "Gorra Deportiva",
    Codigo: "00012",
    Precio: "$20.00",
    Costo: "$10.00",
    Bodega: 500,
    Vitrinas: 200,
    Proveedor: "Natalia Ruiz",
    Categorias: "Accesorios",
  },
  {
    Producto: "Cinturón de Cuero",
    Codigo: "00013",
    Precio: "$40.00",
    Costo: "$25.00",
    Bodega: 120,
    Vitrinas: 60,
    Proveedor: "Santiago Díaz",
    Categorias: "Accesorios",
  },
  {
    Producto: "Lentes de Lectura",
    Codigo: "00014",
    Precio: "$35.00",
    Costo: "$20.00",
    Bodega: 220,
    Vitrinas: 80,
    Proveedor: "Andrea Castillo",
    Categorias: "Accesorios",
  },
  {
    Producto: "Sombrero de Paja",
    Codigo: "00015",
    Precio: "$25.00",
    Costo: "$15.00",
    Bodega: 100,
    Vitrinas: 50,
    Proveedor: "Roberto Morales",
    Categorias: "Accesorios",
  },
  {
    Producto: "Bufanda de Lana",
    Codigo: "00016",
    Precio: "$45.00",
    Costo: "$30.00",
    Bodega: 150,
    Vitrinas: 70,
    Proveedor: "Sofía Romero",
    Categorias: "Ropa",
  },
  {
    Producto: "Pantalones Cortos",
    Codigo: "00017",
    Precio: "$35.00",
    Costo: "$20.00",
    Bodega: 200,
    Vitrinas: 100,
    Proveedor: "Alberto Pérez",
    Categorias: "Ropa",
  },
  {
    Producto: "Vestido de Verano",
    Codigo: "00018",
    Precio: "$70.00",
    Costo: "$50.00",
    Bodega: 80,
    Vitrinas: 30,
    Proveedor: "Isabel Mendoza",
    Categorias: "Ropa",
  },
  {
    Producto: "Chaqueta de Invierno",
    Codigo: "00019",
    Precio: "$200.00",
    Costo: "$150.00",
    Bodega: 50,
    Vitrinas: 20,
    Proveedor: "Manuel Ortiz",
    Categorias: "Ropa",
  },
  {
    Producto: "Camisa Formal",
    Codigo: "00020",
    Precio: "$60.00",
    Costo: "$40.00",
    Bodega: 250,
    Vitrinas: 100,
    Proveedor: "Marta Vargas",
    Categorias: "Ropa",
  },
  {
    Producto: "Botines de Cuero",
    Codigo: "00021",
    Precio: "$130.00",
    Costo: "$90.00",
    Bodega: 120,
    Vitrinas: 40,
    Proveedor: "Diego Castro",
    Categorias: "Calzado",
  },
];
