export default [
  { producto: "Camisetas", porcentaje: 95.5 },
  { producto: "Pantalones", porcentaje: 88.7 },
  { producto: "Zapatos", porcentaje: 92.3 },
  { producto: "Sombreros", porcentaje: 85.1 },
  { producto: "Bufandas", porcentaje: 78.4 },
  { producto: "Guantes", porcentaje: 80.0 },
  { producto: "Calcetines", porcentaje: 96.2 },
  { producto: "Chaquetas", porcentaje: 89.5 },
  { producto: "Faldas", porcentaje: 83.9 },
  { producto: "Vestidos", porcentaje: 91.7 },
  { producto: "Suéteres", porcentaje: 87.6 },
  { producto: "Abrigos", porcentaje: 82.8 },
  { producto: "Trajes", porcentaje: 90.4 },
  { producto: "Bañadores", porcentaje: 76.3 },
  { producto: "Sandalias", porcentaje: 84.5 },
  { producto: "Cinturones", porcentaje: 93.1 },
  { producto: "Gorras", porcentaje: 88.2 },
  { producto: "Mochilas", porcentaje: 94.7 },
  { producto: "Pijamas", porcentaje: 85.9 },
  { producto: "Ropa interior", porcentaje: 97.0 },
];
