const textStyles = {
  RobotoeBanner: {
    fontFamily: "Roboto",
    fontSize: "2.625rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "74px",
    letterSpacing: "0.5px",
  },
  RobotoeBannerBold: {
    fontFamily: "Roboto",
    fontSize: "2.625rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "74px",
    letterSpacing: "0.5px",
  },
  RobotoHeader: {
    fontFamily: "Roboto",
    fontSize: "2.25rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
    letterSpacing: "0.5px",
  },
  RobotoHeaderBold: {
    fontFamily: "Roboto",
    fontSize: "2.25rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
    letterSpacing: "0.5px",
  },
  RobotoTitleBold: {
    fontFamily: "Roboto",
    fontSize: "1.25rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  RobotoTitle: {
    fontFamily: "Roboto",
    fontSize: "1.25rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  RobotoSubtitleBold: {
    fontFamily: "Roboto",
    fontSize: "1.125rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  RobotoSubtitle: {
    fontFamily: "Roboto",
    fontSize: "1.125rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  RobotoBodyBold: {
    fontFamily: "Roboto",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
    letterSpacing: "0.08px",
  },
  RobotoBody: {
    fontFamily: "Roboto",
    fontSize: "1rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
    letterSpacing: "0.08px",
  },
  RobotoRegularBold: {
    fontFamily: "Roboto",
    fontSize: "0.875rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  RobotoRegular: {
    fontFamily: "Roboto",
    fontSize: "0.875rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  RobotoTinyBold: {
    fontFamily: "Roboto",
    fontSize: "0.75rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  RobotoTiny: {
    fontFamily: "Roboto",
    fontSize: "0.75rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
  RobotoNanoBold: {
    fontFamily: "Roboto",
    fontSize: "0.625rem",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "150%",
  },
  RobotoNano: {
    fontFamily: "Roboto",
    fontSize: "0.625rem",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "150%",
  },
};

export default textStyles;
